language: r
sudo : false
cache: packages


r:
  - release

r_packages:
  - mlr
  - ParamHelpers
  - smoof
  - mlrMBO
  - xgboost
  - parallelMap
  - rpart
  - cmaes
  - rgenoud
  - checkmate

r_github_packages:
  - jimhester/covr
  - mlr-org/mlrCPO

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::coveralls()'
